// Code generated by protoc-gen-go from "src/core/connect/mmn/mmn.proto"
// DO NOT EDIT!

package mmn

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"

// Reference proto & math imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf

type Line struct {
	Type             *uint32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Msg              []byte  `protobuf:"bytes,2,req,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *Line) Reset()         { *this = Line{} }
func (this *Line) String() string { return proto.CompactTextString(this) }

type VersionList struct {
	Version          []string `protobuf:"bytes,1,rep,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *VersionList) Reset()         { *this = VersionList{} }
func (this *VersionList) String() string { return proto.CompactTextString(this) }

type Version struct {
	Version          *string `protobuf:"bytes,1,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *Version) Reset()         { *this = Version{} }
func (this *Version) String() string { return proto.CompactTextString(this) }

type Cap struct {
	Capability       []string `protobuf:"bytes,1,rep,name=capability" json:"capability,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *Cap) Reset()         { *this = Cap{} }
func (this *Cap) String() string { return proto.CompactTextString(this) }

type Degraded struct {
	Degraded         *bool  `protobuf:"varint,1,req,name=degraded" json:"degraded,omitempty"`
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *Degraded) Reset()         { *this = Degraded{} }
func (this *Degraded) String() string { return proto.CompactTextString(this) }

type Nonce struct {
	Nonce            *uint64 `protobuf:"varint,1,req,name=nonce" json:"nonce,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *Nonce) Reset()         { *this = Nonce{} }
func (this *Nonce) String() string { return proto.CompactTextString(this) }

type EntitySync struct {
	Entity           *uint64 `protobuf:"varint,1,req,name=entity" json:"entity,omitempty"`
	Key              *string `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	Value            []byte  `protobuf:"bytes,3,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *EntitySync) Reset()         { *this = EntitySync{} }
func (this *EntitySync) String() string { return proto.CompactTextString(this) }

type GlobalSync struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            []byte  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *GlobalSync) Reset()         { *this = GlobalSync{} }
func (this *GlobalSync) String() string { return proto.CompactTextString(this) }

type ChangeRequest struct {
	Id               *uint64        `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Ignores          []uint64       `protobuf:"varint,2,rep,name=ignores" json:"ignores,omitempty"`
	Changes          []*ChangeEntry `protobuf:"bytes,3,rep,name=changes" json:"changes,omitempty"`
	XXX_unrecognized []byte         `json:",omitempty"`
}

func (this *ChangeRequest) Reset()         { *this = ChangeRequest{} }
func (this *ChangeRequest) String() string { return proto.CompactTextString(this) }

type ChangeRequestAck struct {
	Request          *uint64 `protobuf:"varint,1,req,name=request" json:"request,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *ChangeRequestAck) Reset()         { *this = ChangeRequestAck{} }
func (this *ChangeRequestAck) String() string { return proto.CompactTextString(this) }

type PaxosPrepare struct {
	Proposal         *uint64 `protobuf:"varint,1,req,name=proposal" json:"proposal,omitempty"`
	NextChange       *uint64 `protobuf:"varint,2,req,name=next_change" json:"next_change,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *PaxosPrepare) Reset()         { *this = PaxosPrepare{} }
func (this *PaxosPrepare) String() string { return proto.CompactTextString(this) }

type PaxosPromise struct {
	Proposal         *uint64                         `protobuf:"varint,1,req,name=proposal" json:"proposal,omitempty"`
	Changes          []*PaxosPromise_ForwardedChange `protobuf:"bytes,2,rep,name=changes" json:"changes,omitempty"`
	XXX_unrecognized []byte                          `json:",omitempty"`
}

func (this *PaxosPromise) Reset()         { *this = PaxosPromise{} }
func (this *PaxosPromise) String() string { return proto.CompactTextString(this) }

type PaxosPromise_ForwardedChange struct {
	Proposal         *uint64        `protobuf:"varint,1,req,name=proposal" json:"proposal,omitempty"`
	Change           *ChangeRequest `protobuf:"bytes,2,req,name=change" json:"change,omitempty"`
	XXX_unrecognized []byte         `json:",omitempty"`
}

func (this *PaxosPromise_ForwardedChange) Reset()         { *this = PaxosPromise_ForwardedChange{} }
func (this *PaxosPromise_ForwardedChange) String() string { return proto.CompactTextString(this) }

type PaxosNack struct {
	Prepare          *uint64 `protobuf:"varint,1,req,name=prepare" json:"prepare,omitempty"`
	Leader           *uint64 `protobuf:"varint,2,req,name=leader" json:"leader,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *PaxosNack) Reset()         { *this = PaxosNack{} }
func (this *PaxosNack) String() string { return proto.CompactTextString(this) }

type PaxosAccept struct {
	Id               *uint64        `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Request          *uint64        `protobuf:"varint,2,req,name=request" json:"request,omitempty"`
	Proposal         *uint64        `protobuf:"varint,3,req,name=proposal" json:"proposal,omitempty"`
	Changes          []*ChangeEntry `protobuf:"bytes,4,rep,name=changes" json:"changes,omitempty"`
	XXX_unrecognized []byte         `json:",omitempty"`
}

func (this *PaxosAccept) Reset()         { *this = PaxosAccept{} }
func (this *PaxosAccept) String() string { return proto.CompactTextString(this) }

type PaxosAccepted struct {
	Id               *uint64        `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Request          *uint64        `protobuf:"varint,2,req,name=request" json:"request,omitempty"`
	Proposal         *uint64        `protobuf:"varint,3,req,name=proposal" json:"proposal,omitempty"`
	Changes          []*ChangeEntry `protobuf:"bytes,4,rep,name=changes" json:"changes,omitempty"`
	XXX_unrecognized []byte         `json:",omitempty"`
}

func (this *PaxosAccepted) Reset()         { *this = PaxosAccepted{} }
func (this *PaxosAccepted) String() string { return proto.CompactTextString(this) }

type Change struct {
	Id               *uint64        `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Request          *uint64        `protobuf:"varint,2,req,name=request" json:"request,omitempty"`
	Proposal         *uint64        `protobuf:"varint,3,req,name=proposal" json:"proposal,omitempty"`
	Changes          []*ChangeEntry `protobuf:"bytes,4,rep,name=changes" json:"changes,omitempty"`
	XXX_unrecognized []byte         `json:",omitempty"`
}

func (this *Change) Reset()         { *this = Change{} }
func (this *Change) String() string { return proto.CompactTextString(this) }

type ChangeEntry struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            []byte  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	Source           *uint64 `protobuf:"varint,3,opt,name=source" json:"source,omitempty"`
	Target           *uint64 `protobuf:"varint,4,opt,name=target" json:"target,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *ChangeEntry) Reset()         { *this = ChangeEntry{} }
func (this *ChangeEntry) String() string { return proto.CompactTextString(this) }

type ChangeNotification struct {
	Change           *uint64 `protobuf:"varint,1,req,name=change" json:"change,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *ChangeNotification) Reset()         { *this = ChangeNotification{} }
func (this *ChangeNotification) String() string { return proto.CompactTextString(this) }

type ChangeContentRequest struct {
	Change           *uint64 `protobuf:"varint,1,req,name=change" json:"change,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *ChangeContentRequest) Reset()         { *this = ChangeContentRequest{} }
func (this *ChangeContentRequest) String() string { return proto.CompactTextString(this) }

type ChangeMissing struct {
	Change           *uint64 `protobuf:"varint,1,req,name=change" json:"change,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *ChangeMissing) Reset()         { *this = ChangeMissing{} }
func (this *ChangeMissing) String() string { return proto.CompactTextString(this) }

func init() {
}
