// Code generated by protoc-gen-go from "src/core/connect/mmn/mmn.proto"
// DO NOT EDIT!

package mmn

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"

// Reference proto & math imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf

type Line struct {
	VersionList          *VersionList   `protobuf:"bytes,1,opt,name=version_list" json:"version_list,omitempty"`
	Version              *string        `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Cap                  *Cap           `protobuf:"bytes,3,opt,name=cap" json:"cap,omitempty"`
	Degraded             *bool          `protobuf:"varint,4,opt,name=degraded" json:"degraded,omitempty"`
	Nonce                *uint64        `protobuf:"varint,101,opt,name=nonce" json:"nonce,omitempty"`
	Desynchronized       *bool          `protobuf:"varint,102,opt,name=desynchronized" json:"desynchronized,omitempty"`
	Synchronized         *bool          `protobuf:"varint,103,opt,name=synchronized" json:"synchronized,omitempty"`
	Burst                *bool          `protobuf:"varint,104,opt,name=burst" json:"burst,omitempty"`
	EntitySync           *EntitySync    `protobuf:"bytes,105,opt,name=entity_sync" json:"entity_sync,omitempty"`
	GlobalSync           *GlobalSync    `protobuf:"bytes,106,opt,name=global_sync" json:"global_sync,omitempty"`
	Ping                 *bool          `protobuf:"varint,201,opt,name=ping" json:"ping,omitempty"`
	Pong                 *bool          `protobuf:"varint,202,opt,name=pong" json:"pong,omitempty"`
	ChangeRequest        *ChangeRequest `protobuf:"bytes,301,opt,name=change_request" json:"change_request,omitempty"`
	ChangeRequestAck     *uint64        `protobuf:"varint,302,opt,name=change_request_ack" json:"change_request_ack,omitempty"`
	PaxosPrepare         *PaxosPrepare  `protobuf:"bytes,303,opt,name=paxos_prepare" json:"paxos_prepare,omitempty"`
	PaxosPromise         *PaxosPromise  `protobuf:"bytes,304,opt,name=paxos_promise" json:"paxos_promise,omitempty"`
	PaxosNack            *PaxosNack     `protobuf:"bytes,305,opt,name=paxos_nack" json:"paxos_nack,omitempty"`
	PaxosAccept          *PaxosAccept   `protobuf:"bytes,306,opt,name=paxos_accept" json:"paxos_accept,omitempty"`
	PaxosAccepted        *PaxosAccepted `protobuf:"bytes,307,opt,name=paxos_accepted" json:"paxos_accepted,omitempty"`
	Change               *Change        `protobuf:"bytes,308,opt,name=change" json:"change,omitempty"`
	ChangeNotification   *uint64        `protobuf:"varint,401,opt,name=change_notification" json:"change_notification,omitempty"`
	ChangeContentRequest *uint64        `protobuf:"varint,402,opt,name=change_content_request" json:"change_content_request,omitempty"`
	ChangeMissing        *uint64        `protobuf:"varint,403,opt,name=change_missing" json:"change_missing,omitempty"`
	XXX_unrecognized     []byte         `json:",omitempty"`
}

func (this *Line) Reset()         { *this = Line{} }
func (this *Line) String() string { return proto.CompactTextString(this) }

type VersionList struct {
	Versions         []string `protobuf:"bytes,1,rep,name=versions" json:"versions,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *VersionList) Reset()         { *this = VersionList{} }
func (this *VersionList) String() string { return proto.CompactTextString(this) }

type Cap struct {
	Capabilities     []string `protobuf:"bytes,1,rep,name=capabilities" json:"capabilities,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *Cap) Reset()         { *this = Cap{} }
func (this *Cap) String() string { return proto.CompactTextString(this) }

type EntitySync struct {
	Entity           *uint64 `protobuf:"varint,1,req,name=entity" json:"entity,omitempty"`
	Key              *string `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	Value            []byte  `protobuf:"bytes,3,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *EntitySync) Reset()         { *this = EntitySync{} }
func (this *EntitySync) String() string { return proto.CompactTextString(this) }

type GlobalSync struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            []byte  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *GlobalSync) Reset()         { *this = GlobalSync{} }
func (this *GlobalSync) String() string { return proto.CompactTextString(this) }

type ChangeRequest struct {
	Id               *uint64        `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Ignores          []uint64       `protobuf:"varint,2,rep,name=ignores" json:"ignores,omitempty"`
	Changes          []*ChangeEntry `protobuf:"bytes,3,rep,name=changes" json:"changes,omitempty"`
	XXX_unrecognized []byte         `json:",omitempty"`
}

func (this *ChangeRequest) Reset()         { *this = ChangeRequest{} }
func (this *ChangeRequest) String() string { return proto.CompactTextString(this) }

type PaxosPrepare struct {
	Proposal         *uint64 `protobuf:"varint,1,req,name=proposal" json:"proposal,omitempty"`
	NextChange       *uint64 `protobuf:"varint,2,req,name=next_change" json:"next_change,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *PaxosPrepare) Reset()         { *this = PaxosPrepare{} }
func (this *PaxosPrepare) String() string { return proto.CompactTextString(this) }

type PaxosPromise struct {
	Proposal         *uint64                         `protobuf:"varint,1,req,name=proposal" json:"proposal,omitempty"`
	Changes          []*PaxosPromise_ForwardedChange `protobuf:"bytes,2,rep,name=changes" json:"changes,omitempty"`
	XXX_unrecognized []byte                          `json:",omitempty"`
}

func (this *PaxosPromise) Reset()         { *this = PaxosPromise{} }
func (this *PaxosPromise) String() string { return proto.CompactTextString(this) }

type PaxosPromise_ForwardedChange struct {
	Proposal         *uint64        `protobuf:"varint,1,req,name=proposal" json:"proposal,omitempty"`
	Change           *ChangeRequest `protobuf:"bytes,2,req,name=change" json:"change,omitempty"`
	XXX_unrecognized []byte         `json:",omitempty"`
}

func (this *PaxosPromise_ForwardedChange) Reset()         { *this = PaxosPromise_ForwardedChange{} }
func (this *PaxosPromise_ForwardedChange) String() string { return proto.CompactTextString(this) }

type PaxosNack struct {
	Prepare          *uint64 `protobuf:"varint,1,req,name=prepare" json:"prepare,omitempty"`
	Leader           *uint64 `protobuf:"varint,2,req,name=leader" json:"leader,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *PaxosNack) Reset()         { *this = PaxosNack{} }
func (this *PaxosNack) String() string { return proto.CompactTextString(this) }

type PaxosAccept struct {
	Id               *uint64        `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Request          *uint64        `protobuf:"varint,2,req,name=request" json:"request,omitempty"`
	Proposal         *uint64        `protobuf:"varint,3,req,name=proposal" json:"proposal,omitempty"`
	Changes          []*ChangeEntry `protobuf:"bytes,4,rep,name=changes" json:"changes,omitempty"`
	XXX_unrecognized []byte         `json:",omitempty"`
}

func (this *PaxosAccept) Reset()         { *this = PaxosAccept{} }
func (this *PaxosAccept) String() string { return proto.CompactTextString(this) }

type PaxosAccepted struct {
	Id               *uint64        `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Request          *uint64        `protobuf:"varint,2,req,name=request" json:"request,omitempty"`
	Proposal         *uint64        `protobuf:"varint,3,req,name=proposal" json:"proposal,omitempty"`
	Changes          []*ChangeEntry `protobuf:"bytes,4,rep,name=changes" json:"changes,omitempty"`
	XXX_unrecognized []byte         `json:",omitempty"`
}

func (this *PaxosAccepted) Reset()         { *this = PaxosAccepted{} }
func (this *PaxosAccepted) String() string { return proto.CompactTextString(this) }

type Change struct {
	Id               *uint64        `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Request          *uint64        `protobuf:"varint,2,req,name=request" json:"request,omitempty"`
	Proposal         *uint64        `protobuf:"varint,3,req,name=proposal" json:"proposal,omitempty"`
	Changes          []*ChangeEntry `protobuf:"bytes,4,rep,name=changes" json:"changes,omitempty"`
	XXX_unrecognized []byte         `json:",omitempty"`
}

func (this *Change) Reset()         { *this = Change{} }
func (this *Change) String() string { return proto.CompactTextString(this) }

type ChangeEntry struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            []byte  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	Source           *uint64 `protobuf:"varint,3,opt,name=source" json:"source,omitempty"`
	Target           *uint64 `protobuf:"varint,4,opt,name=target" json:"target,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *ChangeEntry) Reset()         { *this = ChangeEntry{} }
func (this *ChangeEntry) String() string { return proto.CompactTextString(this) }

type ChangeNotification struct {
	Change           *uint64 `protobuf:"varint,1,req,name=change" json:"change,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *ChangeNotification) Reset()         { *this = ChangeNotification{} }
func (this *ChangeNotification) String() string { return proto.CompactTextString(this) }

type ChangeContentRequest struct {
	Change           *uint64 `protobuf:"varint,1,req,name=change" json:"change,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *ChangeContentRequest) Reset()         { *this = ChangeContentRequest{} }
func (this *ChangeContentRequest) String() string { return proto.CompactTextString(this) }

type ChangeMissing struct {
	Change           *uint64 `protobuf:"varint,1,req,name=change" json:"change,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *ChangeMissing) Reset()         { *this = ChangeMissing{} }
func (this *ChangeMissing) String() string { return proto.CompactTextString(this) }

func init() {
}
