include $(GOROOT)/src/Make.$(GOARCH)

TARG=oddircd/src/core
GOFILES=\
	main.go\
	id.go\
	user.go\
	userhelper.go\
	channel.go\
	membership.go\
	hooks.go\
	chanhooks.go\
	userhooks.go\
	trie.go

include $(GOROOT)/src/Make.pkg
