include $(GOROOT)/src/Make.$(GOARCH)

TARG=oddircd/src/perm
GOFILES=\
	main.go\
	hooklist.go\
	view.go\
	nick.go\
	data.go\
	join.go\
	message.go\
	defaultview.go\
	defaultdata.go\
	defaultjoin.go\
	defaultmsg.go\
	bans.go\
	defaultbans.go\
	ops.go\
	glob.go

include $(GOROOT)/src/Make.pkg
