include $(GOROOT)/src/Make.$(GOARCH)

TARG=oddircd/src/client
GOFILES=\
	main.go\
	client.go\
	climap.go\
	commands.go\
	modes.go\
	handler.go\
	request.go\
	usercmds.go\
	validate.go\
	hooks.go

include $(GOROOT)/src/Make.pkg
